# https://help.github.com/en/actions/automating-your-workflow-with-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#using-a-specific-shell
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-powershell
# https://github.com/actions/upload-artifact#where-does-the-upload-go
name: PSAppDeployToolkit-Windows-PowerShell
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
permissions:
  contents: read
jobs:
  test:
    name: Run Tests
    runs-on: windows-latest
    strategy:
      fail-fast: true
    steps:
    - name: PowerShellGet Latest
      shell: powershell
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
        # Clone the source and dest repos down to temp.
        git clone -b $env:GITHUB_REF_NAME "https://$API_TOKEN_GITHUB@github.com/$env:GITHUB_REPOSITORY_OWNER/PSAppDeployToolkit.git" ($srcRepo = [System.IO.Path]::GetTempFileName())
        git clone -b main "https://$API_TOKEN_GITHUB@github.com/$env:GITHUB_REPOSITORY_OWNER/website.git" ($dstRepo = [System.IO.Path]::GetTempFileName())

        # Remove the current docs from the source.
        Remove-Item -Path "$dstRepo\docs\reference\functions\*" -Force -Confirm:$false
        Copy-Item -Path "$srcRepo\docs\*.mdx" -Destination "$dstRepo\docs\reference\functions"

        # Commit any changes if found.
        if (git diff-index HEAD)
        {
          git commit -m "Commit of document changes from https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"
          git push origin
        }
